### ISSUE TITLE
ice matrix bias file inconsistency

### ISSUE THREAD

**Issue by esebesty** [hiclib/iced#103]
Hi, I'm trying to use iced 0.5.8 on the raw matrix output of HiC-Pro. Hower, I'm getting inconsistent bin counts.

If I run iced like:

```sh
ice --results_filename {output.icematrix} --filter_low_counts_perc 0.02 \
    --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --base 0 \
    --remove-all-zeros-loci --output-bias 1 {input.matrix} > {log} 2>&1
```

the output files look like this:

```
(iced) [bcro-big ice-matrix main*]$ wc -l N2P_D0_1000000*
 3594245 N2P_D0_1000000.icematrix
    3115 N2P_D0_1000000.icematrix.biases
 3597360 total
(iced) [bcro-big ice-matrix main*]$ head -n 2 N2P_D0_1000000*
==> N2P_D0_1000000.icematrix <==
1	1	3590.512980
1	2	1465.522789

==> N2P_D0_1000000.icematrix.biases <==
nan
3.456610107735157977e-01
```

However, if I check the raw matrix:

```
[bcro-big 1000000 main*]$ wc -l *
    3114 N2P_D0_1000000_abs.bed
 3594245 N2P_D0_1000000.matrix
 3597359 total
[bcro-big 1000000 main*]$ head -n 2 *
==> N2P_D0_1000000_abs.bed <==
chr1	0	1000000	1
chr1	1000000	2000000	2

==> N2P_D0_1000000.matrix <==
1	1	429
1	2	481
```

So the size of the matrices is the same, the bin numbering seems to be ok, both of them start at 1, but:

- the ice matrix bias file seems to have one more line compared to the number of bins in the bed file
- it is a bit counterintuitive to me that I have to specify `--base 0` to get 1 based bin numbers

The resulting bias file breaks the `hicpro2fithic.py` script from HiC-Pro. Some HiC-Pro issues might be relevant: [this](https://github.com/nservant/HiC-Pro/issues/416), [this](https://github.com/nservant/HiC-Pro/issues/389), [this](https://github.com/nservant/HiC-Pro/issues/433).

Can I just simply remove the first line of the bias file? It seems to always contain a `nan` regardless of sample or resolution.

**Comment by NelleV** [comment]
Hello,
This was due to a bug in ice, that I just fixed. If you upgrade to 0.5.9, the behaviour should be as expected.
Thanks for reporting the issue!
N

**Comment by esebesty** [comment]
Thanks for the bugfix!
