### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by Bonnie19920126** [hiclib/iced#57]
Hi,
   I used HiC-Pro to get the ICE normalization matrix implemented by hiclib, I used 1kb resolution, but meet the memory problem, so I split the genome matrix into 24 matrices per chromosome, and get the 24 ICE matrices per chromosome, but the ICE assumption of equal visibility (genome-wide) change to equal visibility (per chromosome). Dose this will effect my result greatly? I don't know whether this is right.

**Comment by NelleV** [comment]
Hi Bonnie,
It can affect the results, but it may not be important depending on the downstream analysis you are running.

**Comment by Bonnie19920126** [comment]
Hi,
  Thank you for your help.
Best wishes
