### ISSUE TITLE
community guidelines links to pastis-issue tracker

### ISSUE THREAD

**Issue by robinweide** [hiclib/iced#62]
In the [docs](http://projects.cbio.mines-paristech.fr/iced/index.html) you link to this issue-tracker: https://github.com/hiclib/pastis.

I think it would be more logical to link to the issue-tracker of iced.

**Comment by NelleV** [comment]
I think the link already links to the issue tracker, unless I'm not looking at the right spot.

**Comment by robinweide** [comment]
In the docs under "CONTACTS":
_If you have any questions or suggestions, please email nelle dot varoquaux at ensmp dot fr, or open a ticket on Github_

The link under github goes to https://github.com/hiclib/pastis/issues

**Comment by NelleV** [comment]
Oh wow. Thanks!

**Comment by NelleV** [comment]
It's fixed. Thanks a lot!
