### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by QianzhaoJ** [hiclib/iced#68]
Hi :
    the script `python /data1/liuzunpeng/04_Softwares/iced-0.5.1/iced/scripts/ice --results_filename hic_results/matrix/$sample/iced/${res}/${sample}_${res}_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 --verbose 1 hic_results/matrix//${sample}/raw/${res}/${sample}_${res}.matrix `
    the error `iced.sh: line 9: 25355 Segmentation fault`
    When I `cat ice` ,I found the line 9 is `from iced.io import loadtxt, savetxt`
    But the `python  /data1/liuzunpeng/04_Softwares/iced-0.5.1/iced/scripts/ice -h` worked ,and the `python ~/iced-0.5.1/iced/tests/test_filter.py` also worked .
    Can you give me some advices?
    Thanks for your time !
Best wishes
Qianzhao

**Comment by QianzhaoJ** [comment]
The problem has been resolved

**Comment by wlhCNU** [comment]
I encountered the same problem, can you tell me how to solve this problem, thanks

**Comment by wlhCNU** [comment]
I encountered the same problem, can you tell me how to solve this problem, thanks @QianzhaoJ
